### ISSUE TITLE
brew install eugenmayer/dockersync/unox throws an error about gunzip

### ISSUE THREAD

**Issue by dimikot** [EugenMayer/homebrew-dockersync#6]
This is a very recent issue (a few weeks ago it worked fine). Could you please take a look? Something is probably wrong with file names on GitHub.

The simplest way to reproduce:
```
~$ brew tap eugenmayer/dockersync
~$ brew reinstall eugenmayer/dockersync/unox
==> Reinstalling eugenmayer/dockersync/unox
==> Downloading https://codeload.github.com/hnsl/unox/tar.gz/0.2.0
Already downloaded: /Users/dimitrik/Library/Caches/Homebrew/unox--0.2.0.gz
Error: Failure while executing; `gunzip -q -N -- /private/tmp/d20180821-56068-1nrf1ej/0.2.0` exited with 1.
```

The file /private/tmp/d20180821-56068-1nrf1ej/0.2.0 doesn't exist, that's why it complains.

Brew is latest, just freshly installed on a new laptop.

**Comment by DiesDasJenes** [comment]
Hi,
i also have the same error message.

MacOS Version: 10.13.6
gunzip (gzip) 1.9
Homebrew 1.7.2

Thanks for looking into this. :)

**Comment by birgitta410** [comment]
I have the same issue.

Here is part of the stacktrace when installing with --verbose and --debug. I think the fact that the file is missing after execution (as DmitryKoterov pointed out) is normal, as it's a temp file, but the actual error seems to be "unknown suffix -- ignored"?

```
...
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb
==> Downloading https://codeload.github.com/hnsl/unox/tar.gz/0.2.0
Already downloaded: /Users/bboeckel/Library/Caches/Homebrew/unox--0.2.0.gz
==> Verifying unox--0.2.0.gz checksum
gunzip -N -- /private/tmp/d20180822-5582-q0mh48/0.2.0
gunzip: /private/tmp/d20180822-5582-q0mh48/0.2.0: unknown suffix -- ignored
Error: Failure while executing; `gunzip -N -- /private/tmp/d20180822-5582-q0mh48/0.2.0` exited with 1. Here's the output:
gunzip: /private/tmp/d20180822-5582-q0mh48/0.2.0: unknown suffix -- ignored

/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/gzip.rb:20:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:119:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:126:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:54:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:170:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:169:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:96:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:74:in `stage'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2018:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1116:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:559:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'
```

**Comment by muratayusuke** [comment]
I had the same issue.

Following dirty patch for homebrew solved this issue for me:
```
diff --git a/Library/Homebrew/unpack_strategy/gzip.rb b/Library/Homebrew/unpack_strategy/gzip.rb
index 2ea64b9b..a3fe1a0c 100644
--- a/Library/Homebrew/unpack_strategy/gzip.rb
+++ b/Library/Homebrew/unpack_strategy/gzip.rb
@@ -15,6 +15,7 @@ def self.can_extract?(path)
     private

     def extract_to_dir(unpack_dir, basename:, verbose:)
+      basename += '.gz'
       FileUtils.cp path, unpack_dir/basename, preserve: true
       quiet_flags = verbose ? [] : ["-q"]
       system_command! "gunzip",
```

**Comment by DiesDasJenes** [comment]
I tried your "dirty patch" and i had to ignore an BuildError but it worked. 

I started the installation with this command: 
```
HOMEBREW_NO_AUTO_UPDATE=1 brew install eugenmayer/dockersync/unox -debug -verbose
```

```
==> /usr/local/Cellar/unox/0.2.0_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore- 
   installed /private/tmp/unox-20180827-15099-1sw3w83
   Created temporary directory: /private/tmp/pip-ephem-wheel-cache-oQMeqr
   Created temporary directory: /private/tmp/pip-req-tracker-Go_gZK
   Created requirements tracker '/private/tmp/pip-req-tracker-Go_gZK'
   Created temporary directory: /private/tmp/pip-install-OZEtCL
   Cleaning up...
   Removed build tracker '/private/tmp/pip-req-tracker-Go_gZK'
   Directory '/private/tmp/unox-20180827-15099-1sw3w83' is not installable. File 'setup.py' not found.
   Exception information:
   Traceback (most recent call last):
   File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-   packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
   File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-   packages/pip/_internal/commands/install.py", line 274, in run
    self.name, wheel_cache
     File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 213, in populate_requirement_set
    wheel_cache=wheel_cache
     File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 216, in from_line
    "not found." % name
   InstallationError: Directory '/private/tmp/unox-20180827-15099-1sw3w83' is not installable. File 'setup.py' not found.
   /usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in 'raise'
   BuildError: Failed executing: /usr/local/Cellar/unox/0.2.0_1/libexec/bin/pip install -v --no-deps --no-   binary :all: --ignore-installed /private/tmp/unox-20180827-15099-1sw3w83
   1. raise
   2. ignore
   3. backtrace
   4. irb
   5. shell
   Choose an action: 2
```

I could install it. Now i have problems with the script where i am using dockersync but i am not sure if its an error related to the BuildError. 

The error from the script is: 
EXCEPTION: #<Docker::Compose::Error: 'up' failed with status 'pid 17061 exit 1'

**Comment by markisherwood** [comment]
Just got this issue myself while trying to re-install unox. The dirty hack allowed me to get through the installation process. I got the same error that @DiesDasJenes did during setup.

**Comment by EugenMayer** [comment]
any chance we get a PR on this? would be great, thanks for investigating

**Comment by AaronSuKounta** [comment]
Same issue

**Comment by ww-hans** [comment]
Same issue here

**Comment by simonfranzen** [comment]
Same issue here

```
Homebrew 1.7.2
Homebrew/homebrew-core (git revision 6ff8b; last commit 2018-08-29)
MacBook-Pro-3:~ simon$ brew install eugenmayer/dockersync/unox -debug -verbose
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb
==> Installing unox from eugenmayer/dockersync
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/bin/sandbox-exec -f /private/tmp/homebrew20180829-54300-10r6j00.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/cask/lib:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb --git --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb
==> Downloading https://codeload.github.com/hnsl/unox/tar.gz/0.2.0
Already downloaded: /Users/simon/Library/Caches/Homebrew/unox--0.2.0.gz
==> Verifying unox--0.2.0.gz checksum
gunzip -N -- /private/tmp/d20180829-54302-16sme28/0.2.0
gunzip: /private/tmp/d20180829-54302-16sme28/0.2.0: unknown suffix -- ignored
Error: Failure while executing; `gunzip -N -- /private/tmp/d20180829-54302-16sme28/0.2.0` exited with 1. Here's the output:
gunzip: /private/tmp/d20180829-54302-16sme28/0.2.0: unknown suffix -- ignored

/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/gzip.rb:20:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:119:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:126:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:54:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:170:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:169:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:96:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:74:in `stage'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2018:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1116:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:559:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'


```

**Comment by mkochendorfer** [comment]
Just confirming here that the fix in https://github.com/d4rky-pl/homebrew-dockersync/commit/cfa29f1bba1a29ad557dedcad88c801b04bf690d does indeed resolve this issue.  Probably just need a PR and merge and it will resolve the issue for everyone

**Comment by EugenMayer** [comment]
Anybody up for a PR? :)

**Comment by ls-jingbo-jin** [comment]
@EugenMayer  PR created: https://github.com/EugenMayer/homebrew-dockersync/pull/7

**Comment by EugenMayer** [comment]
Thanks, should be fixed now
